# Generated by Django 3.2.3 on 2021-06-27 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCAtegoria', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='idCategoria')),
                ('nombreCAtegoria', models.CharField(default='', max_length=50, verbose_name='nombreCategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idCategoria', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='idCategoria')),
                ('nombreServicio', models.CharField(default='', max_length=50, verbose_name='nombreServicio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('userName', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='userName')),
                ('email', models.CharField(default='', max_length=50, verbose_name='email')),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(default='', max_length=50, verbose_name='apellido')),
                ('fechaNacimiento', models.CharField(default='', max_length=20, verbose_name='fechaNacimiento')),
                ('clave', models.CharField(default='', max_length=50, verbose_name='clave')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='rut')),
                ('nombreProveedor', models.CharField(default='', max_length=50, verbose_name='nombreProveedor')),
                ('razonSocial', models.CharField(default='', max_length=50, verbose_name='razonSocial')),
                ('descripcion', models.CharField(default='', max_length=500, verbose_name='descripcion')),
                ('telefono', models.CharField(default='', max_length=50, verbose_name='telefono')),
                ('emailProveedor', models.CharField(default='', max_length=50, verbose_name='emailProveedor')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
        ),
    ]
